const products = [
{ name:"Ruh Chameli", price:899, category:"ruh", img:"https://picsum.photos/300?1", desc:"Natural jasmine fragrance with calming notes."},
{ name:"Ruh Gulab", price:3499, category:"ruh", img:"https://picsum.photos/300?2", desc:"Royal rose fragrance with long-lasting aroma."},
{ name:"Ruh Juhi", price:1299, category:"ruh", img:"https://picsum.photos/300?3", desc:"Soft floral scent with fresh notes."},
{ name:"Ruh Khus", price:199, category:"ruh", img:"https://picsum.photos/300?4", desc:"Earthy vetiver fragrance, cooling feel."},
{ name:"Ruh Motiya", price:2299, category:"ruh", img:"https://picsum.photos/300?5", desc:"Sweet jasmine-based premium fragrance."},
{ name:"Ruh Kadamba", price:4499, category:"ruh", img:"https://picsum.photos/300?6", desc:"Rare exotic floral aroma."},
{ name:"Ruh Kewra", price:3499, category:"ruh", img:"https://picsum.photos/300?7", desc:"Fresh traditional kewra scent."},
{ name:"Ruh Rajnigandha", price:1299, category:"ruh", img:"https://picsum.photos/300?8", desc:"Strong tuberose fragrance."},
{ name:"Ruh Red Champaka", price:1299, category:"ruh", img:"https://picsum.photos/300?9", desc:"Warm floral premium fragrance."},
{ name:"Pink Lotus", price:1499, category:"ruh", img:"https://picsum.photos/300?10", desc:"Soft aquatic lotus fragrance."},
{ name:"Ruh Mogra", price:999, category:"ruh", img:"https://picsum.photos/300?11", desc:"Classic mogra fragrance."},
{ name:"Ruh Red Gulab", price:2199, category:"ruh", img:"https://picsum.photos/300?12", desc:"Deep intense rose fragrance."},
{ name:"Gulab Jal", price:179, category:"water", img:"https://picsum.photos/300?13", desc:"Pure rose water for skin."},
{ name:"Gulab Jal Pasaya", price:349, category:"water", img:"https://picsum.photos/300?14", desc:"Premium distilled rose water."},
{ name:"Shamama", price:249, category:"oil", img:"https://picsum.photos/300?15", desc:"Warm spicy attar blend."},
{ name:"Sandalwood Oil", price:399, category:"oil", img:"https://picsum.photos/300?16", desc:"Pure sandalwood oil."},
{ name:"Mukhallat Guldastaan", price:1299, category:"other", img:"https://picsum.photos/300?17", desc:"Luxury attar blend."},
{ name:"Ruh Gulab Pasaya", price:3499, category:"other", img:"https://picsum.photos/300?18", desc:"High quality rose attar."}
];
